### ISSUE TITLE
Container initial boot fails for database (pg_ctl: cannot be run as root)

### ISSUE THREAD

**Issue by mchubby** [patroni-training/2019#2]
Running docker-compose up -d fails to bring databases containers up and running

```
> docker logs -f demo-patroni1
decompressing image...
2019-10-31 20:38:06,204 INFO: Failed to import patroni.dcs.consul
2019-10-31 20:38:06,214 INFO: Selected new etcd server http://etcd3:2379
2019-10-31 20:38:06,402 ERROR: Failed to get list of machines from http://etcd3:2379/v2: EtcdException(None,)
2019-10-31 20:38:06,402 INFO: Retrying on http://etcd1:2379
2019-10-31 20:38:06,426 ERROR: Failed to get list of machines from http://etcd1:2379/v2: EtcdException(None,)
2019-10-31 20:38:06,426 INFO: Retrying on http://etcd2:2379
2019-10-31 20:38:06,429 ERROR: Failed to get list of machines from http://etcd2:2379/v2: EtcdException(None,)
2019-10-31 20:38:06,429 INFO: waiting on etcd
2019-10-31 20:38:11,431 INFO: Selected new etcd server http://etcd3:2379
2019-10-31 20:38:11,439 INFO: Reaped pid=24, exit status=0
2019-10-31 20:38:11,480 INFO: Lock owner: None; I am patroni1
2019-10-31 20:38:11,948 ERROR:
Traceback (most recent call last):
  File "/patroni/dcs/etcd.py", line 345, in wrapper
    retval = func(self, *args, **kwargs) is not None
  File "/patroni/dcs/etcd.py", line 548, in initialize
    return self.retry(self._client.write, self.initialize_path, sysid, prevExist=(not create_new))
  File "/patroni/dcs/etcd.py", line 329, in retry
    return self._retry.copy()(*args, **kwargs)
  File "/patroni/utils.py", line 254, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 461, in write
    response = self.api_execute(path, method, params=params)
  File "/patroni/dcs/etcd.py", line 219, in api_execute
    return self._handle_server_response(response)
  File "/usr/lib/python3/dist-packages/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/lib/python3/dist-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
etcd.EtcdAlreadyExist: Key already exists : /service/demo/initialize
2019-10-31 20:38:11,968 INFO: failed to acquire initialize lock
2019-10-31 20:38:21,655 INFO: Lock owner: None; I am patroni1
2019-10-31 20:38:22,047 INFO: trying to bootstrap a new cluster
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
2019-10-31 20:38:22,051 INFO: removing initialize key after failed attempt to bootstrap the cluster
2019-10-31 20:38:22,582 INFO: Lock owner: None; I am patroni1
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/patroni/__init__.py", line 148, in patroni_main
    patroni.run()
  File "/patroni/__init__.py", line 119, in run
    logger.info(self.ha.run_cycle())
  File "/patroni/ha.py", line 1310, in run_cycle
    info = self._run_cycle()
  File "/patroni/ha.py", line 1219, in _run_cycle
    return self.post_bootstrap()
  File "/patroni/ha.py", line 1115, in post_bootstrap
    self.cancel_initialization()
  File "/patroni/ha.py", line 1110, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
```

Base image is (Debian 9 patroni v1.5.5)
https://hub.docker.com/layers/patronitraining/patroni/latest/images/sha256-3ed904c7b5b8fbecc0ea519bf43d555d0db4cd7234d5c47bd85dd99bd58ab8af

Docker-compose.yml was only modified to put version: "2.1" for Windows

**Comment by mchubby** [comment]
Works fine in an Ubuntu 19 VM (both with pulled image or self-built). No idea why Docker Desktop would ignore the USER directive, but closing.
